# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Web Archive Collection

description: > 
  A collection of web content harvested from University of Idaho websites.
# baseurl: "/digital/webarchive" # the subpath of your site, e.g. /blog
baseurl: "/webarchive"
# url: "http://www.lib.uidaho.edu" # the base hostname & protocol for your site
url: "http://evanwill.github.io"

# Build settings
markdown: kramdown
